### ISSUE TITLE
db4.8 unable to install on ubuntu (ppa)

### ISSUE THREAD

**Issue by ivo1981** [LIMXTEC/BitCore#1]
I tried following the install manual but got an error on:
sudo add-apt-repository ppa:bitcore/bitcore

Cannot add PPA: 'ppa:~bitcore/ubuntu/bitcore'.
ERROR: '~bitcore' user or team does not exist.

I tried running the precompiled binaries, but this wouldn't work because the ubuntu install is missing dependencies.
I'm now attempting to install them so I can run this bitcore.
I already have a bitcoin bitcore running.
Any ideas?

**Comment by limxdev** [comment]
Did you have tried this guide here?
https://github.com/LIMXTEC/BitCore/blob/master/doc/build-unix.md

**Comment by ivo1981** [comment]
sorry for the slow response am going to try to build from scratch tommorow.
Will update the progress
Thanks for the pointer

**Comment by jamespic** [comment]
The instructions on that page are incorrect, as there is no `bitcore` PPA. I'd guess it should probably read `sudo add-apt-repository ppa:bitcoin/bitcoin`, until the bitcore team creates a PPA.
