### ISSUE TITLE
Android wallet issue.

### ISSUE THREAD

**Issue by vigens** [LIMXTEC/BitCore#10]
Hey. I made a payment from my android wallet on the 22nd of September. It is still showing me message: this payment has not been transmitted yet. How can i sync my wallet or what can i do to get the coins transmitted before tomorrows airdrop?

**Comment by madzebra** [comment]
Hello.
You need to `backup your wallet` and `reset the blockchain` in option menu.
After that you can send coins again.

**Comment by Diamgio** [comment]
Hello. My It doesn't works for paper wallet

**Comment by vigens** [comment]
Its and android wallet. Thank you for response.

**Comment by Diamgio** [comment]
![photo_2017-09-25_16-12-13](https://user-images.githubusercontent.com/32269138/30812949-54fa2c56-a20c-11e7-9e38-a3715a4c14aa.jpg)

Yes, my android wallet. I need totake a paper wallet. Only thing I can do, is click cancel

**Comment by fabiolo1977** [comment]
This Is my problem  my android wallet. I need totake a paper wallet. Only thing I can do, is click cancel

**Comment by dArkjON** [comment]
At the moment we dont have a own Android App.
Please use https://coinomi.com/ for mobile Devices.
