### ISSUE TITLE
Linux bitcoin-qt doesn't work. (Ubuntu 17.04)

### ISSUE THREAD

**Issue by gagarin55** [LIMXTEC/BitCore#12]
Ubuntu 17.04
Bitcore 0.14.1.6

```
$ ./bitcore-qt
./bitcore-qt: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory
```

**Comment by joshafest** [comment]
please configure boost

**Comment by joshafest** [comment]
see your local boost path

**Comment by benzmuircroft** [comment]
link for how to 'configure boost' please.

Same problem

**Comment by dArkjON** [comment]
https://github.com/LIMXTEC/BitCore/blob/master/doc/build-unix.md#dependency-build-instructions-ubuntu--debian

> 
> Options when installing required Boost library files:
> 
> On at least Ubuntu 14.04+ and Debian 7+ there are generic names for the individual boost development packages, so the following can be used to only install necessary parts of boost:
> 
>  sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev
> If that doesn't work, you can install all boost development packages with:
> 
>  sudo apt-get install libboost-all-dev
> BerkeleyDB is required for the wallet.
> 
> For Ubuntu only: db4.8 packages are available here. You can add the repository and install using the following commands:
> 
> sudo apt-get install software-properties-common
> sudo add-apt-repository ppa:bitcore/bitcore
> sudo apt-get update
> sudo apt-get install libdb4.8-dev libdb4.8++-dev

**Comment by jackngai** [comment]
@dArkjON I tried installing libboost (all dev) on Debian 8 and I'm still getting the same error. Does the version matter? I'm only able to pull down the latest 1.62, not the 1.58 listed in the error message.

**Comment by dArkjON** [comment]
libboost_system.so.1.58.0 is needed to start it yes.

We also have 2 different Autoinstaller :
https://github.com/LIMXTEC/Bitcore-BTX-RPC-Installer

Here is a bash also a dockers installer inside
