### ISSUE TITLE
PLEASE: how do I built a STATIC BINARY?

### ISSUE THREAD

**Issue by Adeliscod** [LIMXTEC/BitCore#13]
I need to compile the app in a static form where the binary that outputs doesn't require the installation of more libraries. For example:

"Bitcore: error while loading shared libraries: libboost_program_options.so.1.58.0: cannot open shared object file: No such file or directory." This happens when I move the binary and try to compile it in another server.

Thanks

**Comment by joshafest** [comment]
please, search out for your local boost path, and add it as flags

**Comment by dArkjON** [comment]
https://github.com/LIMXTEC/BitCore/blob/master/doc/build-unix.md#dependency-build-instructions-ubuntu--debian

> Options when installing required Boost library files:
> 
> On at least Ubuntu 14.04+ and Debian 7+ there are generic names for the individual boost development packages, so the following can be used to only install necessary parts of boost:
> 
> sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev
> If that doesn't work, you can install all boost development packages with:
> 
> sudo apt-get install libboost-all-dev
> BerkeleyDB is required for the wallet.
> 
> For Ubuntu only: db4.8 packages are available here. You can add the repository and install using the following commands:
> 
> sudo apt-get install software-properties-common
> sudo add-apt-repository ppa:bitcore/bitcore
> sudo apt-get update
> sudo apt-get install libdb4.8-dev libdb4.8++-dev
