### ISSUE TITLE
How to enable pruning

### ISSUE THREAD

**Issue by ersinpw** [LIMXTEC/BitCore#14]
I would like to enable pruning

**Comment by limxdev** [comment]
-prune=<n> | Reduce storage requirements by enabling pruning (deleting) of old blocks. This allows the pruneblockchain RPC to be called to delete specific blocks, and enables automatic pruning of old blocks if a target size in MiB is provided. This mode is incompatible with -txindex and -rescan. Warning: Reverting this setting requires re-downloading the entire blockchain. (default: 0 = disable pruning blocks, 1 = allow manual pruning via RPC, >550 = automatically prune block files to stay under the specified target size in MiB)
-- | --
