### ISSUE TITLE
Bitcore Core 0.15.0.1 - no sync from scratch- no connection hard coded nodes

### ISSUE THREAD

**Issue by limxdev** [LIMXTEC/BitCore#17]
The Core 0.15.0.1 is nearly done. We have two open task currently.

1. No sync from scratch
---
The wallet connected only with addnode "addnode 188.68.52.172 onetry". 
The connection with lots of nodes is possible. The wallet looks the correct chain high. But the sync is not possible. It is possible to move the chain in the appfolder. After then works the wallet normal.

2. No connection hard coded nodes
---
https://github.com/LIMXTEC/BitCore/blob/0.15/src/chainparams.cpp#L134
The wallet connected only with addnode "addnode 188.68.52.172 onetry" or similar. 

Bounty for this task 100 Bitcore. (Only for tested pullrequest)

**Comment by joshafest** [comment]
#19
