### ISSUE TITLE
 latest xenial release - can't run bitcore-qt

### ISSUE THREAD

**Issue by mikakun** [LIMXTEC/BitCore#18]
### Describe the issue

latest xenial release

!root : 
Impossible d’obtenir un verrou sur le répertoire de données /home/mika/.bitcore. BitCore Core fonctionne probablement déjà. Permission non accordée.

(impossible to get a lock on data directory)

root : 

*Impossible de se lier à 0.0.0.0:8555 sur cet ordinateur. BitCore Core fonctionne probablement déjà.
(impossible to link to 0.0.0.0:8555 bitcore probably already running
* Échec d'écoute sur un port quelconque. Utiliser -listen=0 si vous le voulez.
(fail to listen on any port) 

### Machine specs:
- OS: ubuntu 16.04
- CPU: i7
- RAM:12gb
- Disk size: 256
- Disk Type (HD/SDD): sdd

did i miss some dependencies ? (i have b3coin running fine)

**Comment by dArkjON** [comment]
> (impossible to link to 0.0.0.0:8555 bitcore probably already running

It looks like your Port is blocked or a other coin already running on Port 8555.
Try to use a other a other Port or close other Wallets before starting bitcore.
