### ISSUE TITLE
Fresh Windows 10 Install, Bitcore-qt crashes

### ISSUE THREAD

**Issue by donceaser** [LIMXTEC/BitCore#20]
This issue tracker is only for technical issues related to bitcore-core.

General bitcore questions and/or support requests and are best directed to the [bitcoretalk.io forums](https://bitcoretalk.io/).

For reporting security issues, please contact the BitCore developers on the #bitcore-dev Freenode IRC channel or alternatively you can email us at contact@bitcore.org.

### Describe the issue
After reinstalling windows 10,  I downloaded the bitcore wallets but when I start bitcore-qt, starts loading wallet. it first pops up and "Error reading wallet.dat! All keys read correctly, but transaction data or address book entries might be missing or incorrect."  This happens on first run.  Then when I click 'ok' it says.. "Error: A fatal internal error occurred, see debug.log for details"
#### If so, please list the steps to reproduce below:
1. Run Bitcore-qt
2. 
3.

### Expected behaviour
The wallet should run

### Actual behaviour
it crashes

### Screenshots.
![readingwallet](https://user-images.githubusercontent.com/32930509/34090610-43c79e4e-e386-11e7-9689-9f25e860e87b.PNG)
![readingwallet](https://user-images.githubusercontent.com/32930509/34090624-5952ab3c-e386-11e7-978d-8e4052db6daa.PNG)

### What version of bitcore-core are you using?
Version v0.14.1.6-g814d134 an official binary.
### Machine specs:
- OS: Windows 10
- CPU: Intel Core i7 2600
- RAM: 16GB
- Disk size: 1TB
- Disk Type (HD/SDD): HD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by limxdev** [comment]
Please save your wallet.dat in your appfolder/backups.

After then install the bitcore wallet with our windows installer.

**Comment by donceaser** [comment]
I had it installed and working before, I backed up the wallet. I reinstalled windows 10, downloaded the windows installer, opened, and this happened.

**Comment by dArkjON** [comment]
Please use the 15.1 and try the Wallet Repair Tab in the Debug Window.
