### ISSUE TITLE
crypto/libbitcore_crypto.a: error adding symbols: Bad value

### ISSUE THREAD

**Issue by tnkmt** [LIMXTEC/BitCore#25]
I am trying to buld the 0.15 branch on Ubuntu 16.04.3 LTS.

    leveldb/util/logging.cc: In function ‘bool leveldb::ConsumeDecimalNumber(leveldb::Slice*, uint64_t*)’:
    leveldb/util/logging.cc:58:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
               (v == kMaxUint64/10 && delta > kMaxUint64%10)) {
                                            ^
      CXX      leveldb/util/leveldb_libleveldb_a-options.o
      CXX      leveldb/util/leveldb_libleveldb_a-status.o
      CXX      leveldb/port/leveldb_libleveldb_a-port_posix.o
    leveldb/port/port_posix.cc: In function ‘bool leveldb::port::HasAcceleratedCRC32C()’:
    leveldb/port/port_posix.cc:60:15: warning: ‘ecx’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       return (ecx & (1 << 20)) != 0;
                   ^
      AR       leveldb/libleveldb.a
      CXX      leveldb/port/leveldb_libleveldb_sse42_a-port_posix_sse.o
      AR       leveldb/libleveldb_sse42.a
      CXX      leveldb/helpers/memenv/leveldb_libmemenv_a-memenv.o
      AR       leveldb/libmemenv.a
      CXXLD    bitcored
    /usr/bin/ld: crypto/libbitcore_crypto.a(crypto_libbitcore_crypto_a-blake.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
    crypto/libbitcore_crypto.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    Makefile:3750: recipe for target 'bitcored' failed
    make[2]: *** [bitcored] Error 1
    make[2]: Leaving directory '/home/user/src/BitCore/src'
    Makefile:9737: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/home/user/src/BitCore/src'
    Makefile:741: recipe for target 'all-recursive' failed
    make: *** [all-recursive] Error 1

Possibly related to  #24.

**Comment by nalply** [comment]
Same for me on the main branch. 

    ./configure --enable-shared

didn't help.

**Comment by minerport** [comment]
I have the same issue after running sudo make, have we found a solution?

**Comment by nalply** [comment]
I gave up

**Comment by nalply** [comment]
I gave up

**Comment by minerport** [comment]
i figured it out

**Comment by minerport** [comment]
but now only  one node and it is unreachable anyone have a list

**Comment by joshafest** [comment]
Please disable hardening

**Comment by dArkjON** [comment]
> Please disable hardening

This working great, on error just try `./configure --disable-hardening` and then `make` again.
