### ISSUE TITLE
Mac version won't start. Just crashes. Sent crash report.

### ISSUE THREAD

**Issue by AtomCollector** [LIMXTEC/BitCore#32]
<img width="434" alt="screen shot 2018-02-04 at 19 05 08" src="https://user-images.githubusercontent.com/36136988/35781183-6a2afc4c-09de-11e8-9ea6-08684435b0e3.png">

**Comment by bradklynsmith** [comment]
Have had the exact issue as AtomCollector

**Comment by limxdev** [comment]
I have it compile with Openssl 1.0.2n .. i think that is for lots of users a problem. I want to give you later a other version.

**Comment by Woodsyde** [comment]
I don't want your fucking coin, Stick it up your ass

**Comment by limxdev** [comment]
Thank you for your feedback.

**Comment by joshafest** [comment]
@limxdev , it has nothing to do with OpenSSL

**Comment by joshafest** [comment]
@limxdev , 
Please run 
make deploy

**Comment by limxdev** [comment]
We have already a new wallet.
