### ISSUE TITLE
Windows 10 Bitcore v0.15.0.2 Text is Small and Doesn't Scale with 4K

### ISSUE THREAD

**Issue by trongod05** [LIMXTEC/BitCore#33]
### Describe the issue
When you launch the client on a 4K screen the text is too small to read.  It doesn't scale.

#### If so, please list the steps to reproduce below:
1. Launch the client on a 4K screen

### Expected behaviour
The text should scale according to your resolution.

### Actual behaviour
Text is too small to read.

### Screenshots.
![bitcore](https://user-images.githubusercontent.com/2983459/36079847-460bffa4-0f4d-11e8-8508-17d56ed0a9e1.png)

### What version of bitcore-core are you using?
v0.15.0.2-gba8ed3a93be (32-bit)

### Machine specs:
- OS: Windows 10
- CPU: Intel
- RAM: 32G
- Disk size: 256G
- Disk Type (HD/SDD): SDD

**Comment by repsac-by** [comment]
The new interface in linux is also not scalable. Earlier in 0.14.1.6 the interface was better and all was well.

**Comment by limxdev** [comment]
I have made a 4 K Version for Windows... please test it and give me feedback.

Kind Regards Christian
https://github.com/LIMXTEC/BitCore/releases/download/0.15.0.2/5.Windows_Bitcore-qt-4K.exe

**Comment by Woodsyde** [comment]
I never got nothing, I gave up

**Comment by trongod05** [comment]
Hello Christian,

Well, the fonts for the balances area are working correctly.  However, the Recent Transactions section is jumbled up a bit.

![bitcore4k](https://user-images.githubusercontent.com/2983459/36462807-3fec1d76-168b-11e8-9202-f9cf77b82872.png)

**Comment by limxdev** [comment]
Okay try this build here.
https://github.com/LIMXTEC/BitCore/releases/download/0.15.0.2/5.bitcore-qt_classic_design.exe

**Comment by trongod05** [comment]
Hello Christian!  Thanks for this build! The classic look works.  The fonts scale accordingly.  I think one thing that I probably should have mentioned in the original post, but you may have already been aware of, was that when you use a 4K resolution you usually have to set a scale value in the OS to pump up the size of the fonts and icons etc... That being said I have my resolution set to 3840x2160 with a scale of 200%.  Maybe these variables play a role in how the 4K build is displaying?

**Comment by limxdev** [comment]
We have installed for Bitcore 0.15 a css system. That works good for graphics and pics but 4K support is currently not correct possible for all Qt versions.
Thank you for your feedback!
