### ISSUE TITLE
No rule to make target `bitcored.1'

### ISSUE THREAD

**Issue by llamafilm** [LIMXTEC/BitCore#35]
There is no binary available to download for the latest 0.15.0.2, so I am trying to build from source.  I get the following error:
```
make[1]: *** No rule to make target `bitcored.1', needed by `all-am'.  Stop.
make: *** [all-recursive] Error 1
```

Full compiler output attached.  I'm running Sierra 10.12.6 with all dependencies installed through MacPorts.
[make log.txt](https://github.com/LIMXTEC/BitCore/files/1745078/make.log.txt)

**Comment by 88plug** [comment]
Go into doc/man and rename all litecoin and litecoind files to be bitcore and bitcored

**Comment by joshafest** [comment]
fixed
