### ISSUE TITLE
Version 0.15.0.2: Wrong checksum linux.Ubuntu.16.04.LTS_non_static.tar.gz

### ISSUE THREAD

**Issue by Kaosys** [LIMXTEC/BitCore#37]
The SHA256 checksum for the file `linux.Ubuntu.16.04.LTS_non_static.tar.gz` of version 0.15.0.2 appears to be wrong on your releases site (https://github.com/LIMXTEC/BitCore/releases).

The site says `09CBED2086B10881EEFAA8D89A18B626B916E41531F980D7FE0CE1278CEBFE14` while when downloaded and `sha256sum` is called, checksum `c2440dacda1534c156ad17ad6d517a3393eeadc95e04223b503492b09a218a2a` is displayed.

Could you please look into that?

**Comment by dArkjON** [comment]
Fixed with new release
