### ISSUE TITLE
Default rpcport 8556 conflicts with megacoin

### ISSUE THREAD

**Issue by g1itch** [LIMXTEC/BitCore#39]
### Steps to reproduce
1. `/usr/bin/bitcored -daemon`

### Expected behaviour
Running bitcored daemon

### Actual behaviour
`$ tail debug.log`

> 2018-06-13 07:30:29 Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
> 2018-06-13 07:30:29 Using 4 threads for script verification
> 2018-06-13 07:30:29 scheduler thread start
> 2018-06-13 07:30:29 Binding RPC on address :: port 8556 failed.
> 2018-06-13 07:30:29 Binding RPC on address 0.0.0.0 port 8556 failed.
> 2018-06-13 07:30:29 Unable to bind any endpoint for RPC server
> 2018-06-13 07:30:29 Error: Unable to start HTTP server. See debug log for details.
> 2018-06-13 07:30:29 scheduler thread interrupt
> 2018-06-13 07:30:29 PrepareShutdown: In progress...
> 2018-06-13 07:30:29 Shutdown: done

`# netstat -ap | grep 8556`
> tcp        0      0 localhost:8556            0.0.0.0:*               LISTEN      9747/megacoind

I use 0.15.0.3 - both bitcored and megacoind 

It's probably [this line](../blob/0.15/src/chainparamsbase.cpp#L35).

**Comment by dArkjON** [comment]
We changed Megacoin to Port : 7952 a new release will follow the next days.
https://github.com/LIMXTEC/Megacoin/commit/ec48c4f86df81ade4bd5779416c5be3fb3f1cb86

**Comment by g1itch** [comment]
OK, thanks.
