### ISSUE TITLE
[Android 0.14.1.6] Restore Wallet doesn't restore balance

### ISSUE THREAD

**Issue by TheButterZone** [LIMXTEC/BitCore#45]
I have it copied in both internal storage top level directory /Download & external SD card top level directory /Download

Yet I get the "No wallet backup was found. Make sure it is placed in external storage (/Download)." message anyway.

ETA1: I generated a new backup file & attempted to restore it with apparent pass success, now I guess I'm waiting for peers...

ETA2: ... that apparently don't exist because this wallet was abandoned for Coinomi.

How do you get your private keys out of your original BTX Android wallet backup file?

**Comment by TheButterZone** [comment]
How do you get your private keys out of your original BTX Android wallet backup file?

**Comment by Woodsyde** [comment]
Stick it up your ass!
