### ISSUE TITLE
SHA256 sum for OSX

### ISSUE THREAD

**Issue by TheButterZone** [LIMXTEC/BitCore#6]
Some benefit to using MD5 just for OSX when you can put _shasum -a 256 [path]_ in Terminal?

**Comment by limxdev** [comment]
I update later the OSX Sha256 hash sum. It is only a test build.

**Comment by madzebra** [comment]
Earlier I posted sha256 sums for my builds. But it seems to me nobody cared. So I've started posting md5 because the command is shorter. Now that I see the interest I'll come back to sha256. Thanks.
