### ISSUE TITLE
latest wallet with boostrap error

### ISSUE THREAD

**Issue by N8Thrasher** [LIMXTEC/BitCore#63]
win7-x64
![Capture](https://user-images.githubusercontent.com/24593637/80366987-f4176c80-8892-11ea-9004-7d6a81a24514.PNG)

**Comment by limxdev** [comment]
https://www.reddit.com/r/bitcore_btx/wiki/index/odarhom_faq

Hello,

please read the faq.

INSTALLATION
The first time you run version 0.9.8.x or newer, your chainstate database will be converted to a new format, which will take anywhere from a few minutes to half an hour, depending on the speed of your machine.

We strictly recommend to remove the folder "chainstate" and "blocks". Do not touch or remove your wallet.dat.
In some cases there were unforeseen error messages insofar as they did not completely new synchronize the old chain.

You can also just replace the local blockchain with the zip.

**Comment by limxdev** [comment]
If you have the same error again. Then delete everything except the **wallet.dat** !! and run the installer again.

**Comment by N8Thrasher** [comment]
> If you have the same error again. Then delete everything except the **wallet.dat** !! and run the installer again.

I did, it does "rewinding blocks" for 30 mins on splash then open the wallet gui then that error happens.

**Comment by limxdev** [comment]
Okay then use please the installer without bootstrap.  Please delete everythin again except the wallet.dat !!
