### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by jddebug** [LIMXTEC/BitCore#69]
I have the older core wallet and it will not connect to peers. It is version 0.15.2.0 for the Mac.

I am hoping to access my BTX. Is there a newer Mac wallet that can access my current wallet.dat?

**Comment by limxdev** [comment]
We are working on fixing the problem.

**Comment by bitcore-btx** [comment]
Please try it with version 0.90.9.10
https://github.com/bitcore-btx/BitCore/releases/tag/0.90.9.10
