### ISSUE TITLE
Memory leak in miner under Windows 10

### ISSUE THREAD

**Issue by almaniac** [LIMXTEC/BitCore#7]
### Describe the issue
There is a memory leak in the miner (gpu) using an NVidia 1070 under Windows 10 (latest NVidia driver).  Over a few hours the ccminer process consumes all the available memory on the machine;  in my case 32GB.

#### If so, please list the steps to reproduce below:
1. Run the miner.
2. Wait.

### Expected behaviour
There should not be a memory leak.

### Actual behaviour
There is a memory leak.

### What version of bitcore-core are you using?
Using the latest miner under https://github.com/LIMXTEC/BitCore/releases

### Machine specs:
- OS: Windows 10
- CPU: Core i7
- RAM: 32GB
- Disk size: 1 TB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
no logs are produced by the miner.

**Comment by joshafest** [comment]
it is miner issue, I think.

**Comment by dArkjON** [comment]
We not longer offer this Miner for Download. There is a SP2 Miner now, maybe check https://www.bitcorepool.cc/
