### ISSUE TITLE
Can't sync wallet

### ISSUE THREAD

**Issue by Haley-Wong** [LIMXTEC/BitCore#70]
I downloaded version 0.90.9.0 (bitcore-osx64.dmg
) MacOS wallet, but it cannot synchronize any blocks. How can I update my wallet on MacOS?

**Comment by limxdev** [comment]
We are working on fixing the problem.

**Comment by bitcore-btx** [comment]
Please try it with version 0.90.9.10
https://github.com/bitcore-btx/BitCore/releases/tag/0.90.9.10

**Comment by User-23173** [comment]
please allow my withdrawal to this address: TAuQg5GtVrVr5cE9iBSJw94B67xr1UWfsC
