### ISSUE TITLE
False positive detected on virus total and ESET NOD32, etc

### ISSUE THREAD

**Issue by WageSlave** [LIMXTEC/BitCore#8]
Virus detected. Novice users are unable to determine if it is safe. Also you seem to have an imposter, bitcore.io

**Comment by limxdev** [comment]
Can you give more infos? Thank you.

**Comment by DJPlaya** [comment]
This also includes Sparta based Bowsers and Sophos

**Comment by DocSnyd3r2** [comment]
Maybe you can upload to virustotal and provide a link.
