### ISSUE TITLE
Errors building Linux wallet

### ISSUE THREAD

**Issue by iSnow** [LIMXTEC/BitCore#9]
user@zbox:~/Downloads/Bitcore-0.14.1.6$ autoconf
configure.ac:32: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:36: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:186: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:219: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:267: error: possibly undefined macro: AC_CHECK_LIB
configure.ac:819: error: possibly undefined macro: AC_CHECK_HEADER

user@zbox:~/Downloads/Bitcore-0.14.1.6$ automake --add-missing 
/usr/share/automake-1.15/am/depend2.am: error: am__fastdepCC does not appear in AM_CONDITIONAL
/usr/share/automake-1.15/am/depend2.am:   The usual way to define 'am__fastdepCC' is to add 'AC_PROG_CC'
/usr/share/automake-1.15/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/share/automake-1.15/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/usr/share/automake-1.15/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
/usr/share/automake-1.15/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/usr/share/automake-1.15/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/share/automake-1.15/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
src/Makefile.am: error: C source seen but 'CC' is undefined
src/Makefile.am:   The usual way to define 'CC' is to add 'AC_PROG_CC'
src/Makefile.am:   to 'configure.ac' and run 'autoconf' again.
/usr/share/automake-1.15/am/depend2.am: error: am__fastdepCXX does not appear in AM_CONDITIONAL
/usr/share/automake-1.15/am/depend2.am:   The usual way to define 'am__fastdepCXX' is to add 'AC_PROG_CXX'
/usr/share/automake-1.15/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/share/automake-1.15/am/depend2.am: error: am__fastdepOBJCXX does not appear in AM_CONDITIONAL
/usr/share/automake-1.15/am/depend2.am:   The usual way to define 'am__fastdepOBJCXX' is to add 'AC_PROG_OBJCXX'
/usr/share/automake-1.15/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
parallel-tests: installing 'build-aux/test-driver'
/usr/share/automake-1.15/am/check2.am: error: am__EXEEXT does not appear in AM_CONDITIONAL

### Describe the issue

Cannot build, automake and autoconf barf on Ubuntu 17.04 & 16.04

### Can you reliably reproduce the issue?

yes 

#### If so, please list the steps to reproduce below:
Trying to build, see above

### What version of bitcore-core are you using?
Linux download from https://github.com/LIMXTEC/BitCore/releases/tag/0.14.1.6

**Comment by joshafest** [comment]
please run ./autogen.sh again

**Comment by iSnow** [comment]
Doesn't really help: 

user@zbox:~/Downloads/BitCore$ ./autogen.sh
configure.ac:28: installing 'build-aux/install-sh'
configure.ac:28: installing 'build-aux/missing'
Makefile.am:8: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:8:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:8:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:8:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:8:   its definition is in aclocal's search path.
Makefile.am: installing 'build-aux/depcomp'
/usr/share/automake-1.15/am/depend2.am: error: am__fastdepCXX does not appear in AM_CONDITIONAL
/usr/share/automake-1.15/am/depend2.am:   The usual way to define 'am__fastdepCXX' is to add 'AC_PROG_CXX'
/usr/share/automake-1.15/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/share/automake-1.15/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/usr/share/automake-1.15/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
/usr/share/automake-1.15/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/usr/share/automake-1.15/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/share/automake-1.15/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
Makefile.am: error: C++ source seen but 'CXX' is undefined
Makefile.am:   The usual way to define 'CXX' is to add 'AC_PROG_CXX'
Makefile.am:   to 'configure.ac' and run 'autoconf' again.
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1

**Comment by madzebra** [comment]
Take a look at this document https://github.com/LIMXTEC/BitCore/blob/master/doc/build-unix.md

Especially, `dependencies` section and the steps to build.

Clearly, you don't have `libtool` installed.

**Comment by limxdev** [comment]
You can try that here:

Commandline: apt-get install python-qt4 python-pip
Commandline: apt-get install libboost-program-options-dev
Commandline: apt-get install libboost-all-dev
Commandline: apt-get install autoconf libtool pkg-config
Commandline: apt-get install libboost-all-dev libssl-dev libevent-dev
Commandline: apt-get install libdb5.3++
Commandline: apt-get install libqrencode-dev
Commandline: apt-get install libminiupnpc-dev
Commandline: apt-get install software-properties-common
Commandline: apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
steve can you add this list of dependencies to the git and documentation? It's needed to get the wallet to work on ubuntu and such:

**Comment by dArkjON** [comment]
Looks like solved.
